name: Generate NuGet Package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "nuget"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: |
            6.x
            8.x
            10.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Generate NuGet Package
        run: dotnet pack -c Release --no-restore

      - name: Upload Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: Ace4896.DBus.Services.Secrets
          path: src/DBus.Services.Secrets/bin/Release/Ace4896.DBus.Services.Secrets.*.nupkg
